accounts/urls.py
from django.urls import path

from .views import signup

urlpatterns = [
    path('signup/', signup, name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
     views.post_detail,
     name='post_detail'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls', namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
             self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    picture = models.ImageField(blank=True, null=True,
                                upload_to='blog/%Y/%m/%d')
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.was_status = self.status

    def save(self, *args, **kwargs):
        if self.status == 'published' and self.status != self.was_status:
            self.publish = timezone.now()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
               args=[self.publish.year,
               self.publish.month,
               self.publish.day,
               self.slug])

    def get_change_url(self):
        link = reverse('admin:blog_post_change', args=(self.id,))
        return link

    def next_published(self):
        next_post = (Post.objects
                    .filter(status='published', publish__gt=self.publish)
                    .exclude(id=self.id)
                    .order_by('publish')
                    .first())
        return next_post

    def prev_published(self):
        prev_post = (Post.objects
                    .filter(status='published', publish__lt=self.publish)
                    .exclude(id=self.id)
                    .order_by('-publish')
                    .first())
        return prev_post

accounts/views.py
from django.shortcuts import render

# from django.contrib.auth.forms import UserCreationForm
# from django.urls import reverse_lazy
# from django.views import generic


# class SignUpView(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('login')
#     template_name = 'signup.html'


from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,
                                password=raw_password)
            login(request, user)
            user.is_staff=True
            permission = Permission.objects.get(name='Can change post')
            user.user_permissions.add(permission)
            user.save()
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post, tag_slug=None):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day
    )

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    change_page = post.get_change_url()
    next_page = post.next_published()
    prev_page = post.prev_published()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'change_page': change_page,
                   'next_page': next_page,
                   'prev_page': prev_page,
                   'tag': tag})

accounts/templates/signup.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
 <div id="content">
  {% block content %}
      {% endblock %}
    </div>
 <div id="sidebar">
    <h2><a href="{% url 'blog:post_list' %}">Blog</a></h2>
    {% if user.is_authenticated %}
      <p>Hi {{ user.username }}!</p>
      <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
      <p>or</p>
      <a href="{% url 'signup' %}">Sign up</a>
    {% endif %}
 </div></body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
 <span class="step-links">
  {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
    <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>

  {% if request.user.is_authenticated %}
    <a href="{{ change_page }}">link to admin panel</a>
  {% endif %}

  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  <p class="info">
    Created {{ post.created }}
  </p>
  <p class="info">
    Updated {{ post.updated }}
  </p>
  {% if post.picture %}
    <img src="{{ post.picture.url }}">
  {% endif %}

  {{ post.body|linebreaks }}

  <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>

  {% if next_page %}
      <a href="{{ next_page.get_absolute_url }}">Next Post</a>
  {% endif %}

  {% if prev_page %}
      <a href="{{ prev_page.get_absolute_url }}">Previous Post</a>
  {% endif %}



{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>

  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
       {{ post.title }}
      </a>
    </h2>

    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}

  {% include "../pagination.html" with page=posts %}

{% endblock %}

blog/templates/pagination.html
<div class="pagination">
 <span class="step-links">
  {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
    <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
</div>